# Generate the full classification script 
with open('classify_layers.py', 'w') as f:
    f.write("""#!/usr/bin/env python3
import yaml
from pathlib import Path
from collections import defaultdict

RULES = [
    (lambda n: n.startswith('g37_electric_'), 'electric_grid', 'electricidad', 'P0'),
    (lambda n: 'generadores_electricidad' in n, 'electric_grid', 'electricidad', 'P0'),
    (lambda n: n.startswith('g37_agua_w_'), 'agua_potable', 'agua', 'P0'),
    (lambda n: n.startswith('g37_agua_ww_'), 'aguas_residuales', 'agua', 'P0'),
    (lambda n: n.startswith('g37_agua_aaa_'), 'agua_admin', 'agua', 'P1'),
    (lambda n: n.startswith('g37_telecom_'), 'telecomunicaciones', 'telecom', 'P0'),
    (lambda n: n == 'g35_viales_carreteras_estatales_2017', 'vial', 'transporte', 'P0'),
    (lambda n: n == 'g35_viales_carreteras_estatales_segmentadas_2021', 'vial', 'transporte', 'P0'),
    (lambda n: n == 'g35_viales_puentes_2010', 'vial', 'transporte', 'P0'),
    (lambda n: n == 'g35_viales_plazas_rampas_peaje_2018', 'vial', 'transporte', 'P0'),
    (lambda n: n.startswith('g35_viales_'), 'vial', 'transporte', 'P1'),
    (lambda n: n.startswith('g35_aerea_'), 'aerea', 'transporte', 'P1'),
    (lambda n: n.startswith('g35_maritima_'), 'maritima', 'transporte', 'P1'),
    (lambda n: n.startswith('g35_colectiva_tren_urbano_alineacion'), 'transporte_colectivo', 'transporte', 'P1'),
    (lambda n: n.startswith('g35_colectiva_tren_urbano_detalle'), 'transporte_colectivo', 'transporte', 'P1'),
    (lambda n: n.startswith('g35_colectiva_tren_urbano_estaciones'), 'transporte_colectivo', 'transporte', 'P1'),
    (lambda n: n.startswith('g35_colectiva_rutas_porteadores'), 'transporte_colectivo', 'transporte', 'P1'),
    (lambda n: n.startswith('g35_colectiva_'), 'transporte_colectivo', 'transporte', 'P2'),
    (lambda n: n.startswith('g35_bienes_raices_'), 'bienes_raices', 'administrativo', 'P2'),
    (lambda n: n.startswith('g33_dotacional_salud_'), 'salud', 'dotaciones', 'P0'),
    (lambda n: n.startswith('g33_seguridad_refugios_'), 'seguridad', 'dotaciones', 'P0'),
    (lambda n: n.startswith('g33_seguridad_'), 'seguridad', 'dotaciones', 'P1'),
    (lambda n: n.startswith('g33_dotacional_educacion_'), 'educacion', 'dotaciones', 'P1'),
    (lambda n: n.startswith('g33_dotacional_'), 'gobierno', 'dotaciones', 'P1'),
    (lambda n: 'riesgo_inunda_floodzone' in n, 'inundacion', 'riesgos', 'P0'),
    (lambda n: 'riesgo_inunda_firms' in n, 'inundacion', 'riesgos', 'P0'),
    (lambda n: 'riesgo_inunda_limwa' in n, 'inundacion', 'riesgos', 'P0'),
    (lambda n: 'riesgo_inunda_erosion' in n, 'inundacion', 'riesgos', 'P0'),
    (lambda n: 'riesgo_inunda_model_intrusion' in n, 'inundacion', 'riesgos', 'P0'),
    (lambda n: 'riesgo_inunda_shoreline' in n, 'inundacion', 'riesgos', 'P0'),
    (lambda n: 'riesgo_inunda_stream' in n, 'inundacion', 'riesgos', 'P0'),
    (lambda n: 'riesgo_inunda_cross_section' in n, 'inundacion', 'riesgos', 'P0'),
    (lambda n: 'riesgo_inunda_s_fld_haz' in n, 'inundacion', 'riesgos', 'P1'),
    (lambda n: 'riesgo_inunda_' in n, 'inundacion', 'riesgos', 'P2'),
    (lambda n: 'riesgo_geol_deslizamientos' in n, 'geologico', 'riesgos', 'P0'),
    (lambda n: 'riesgo_geol_licuacion' in n, 'geologico', 'riesgos', 'P0'),
    (lambda n: 'riesgo_geol_sismos_historicos' in n, 'geologico', 'riesgos', 'P0'),
    (lambda n: 'riesgo_geol_sismos_1989' in n, 'geologico', 'riesgos', 'P0'),
    (lambda n: 'riesgo_geol_' in n, 'geologico', 'riesgos', 'P1'),
    (lambda n: n.startswith('g27_sea_level_rise_'), 'marejada_slr', 'riesgos', 'P0'),
    (lambda n: n.startswith('g27_potential_inund_'), 'marejada_slr', 'riesgos', 'P0'),
    (lambda n: n == 'g03_legales_isla_pr', 'limites', 'administrativo', 'P0'),
    (lambda n: n == 'g03_legales_municipios_2023', 'limites', 'administrativo', 'P0'),
    (lambda n: n == 'g03_legales_barrios_2023', 'limites', 'administrativo', 'P0'),
    (lambda n: n == 'g03_legales_barrios_pueblo_2015', 'limites', 'administrativo', 'P0'),
    (lambda n: n.startswith('g03_legales_municipios_'), 'limites', 'administrativo', 'P1'),
    (lambda n: n.startswith('g03_legales_barrios_'), 'limites', 'administrativo', 'P1'),
    (lambda n: n.startswith('g03_legales_'), 'limites', 'administrativo', 'P1'),
    (lambda n: n.startswith('g03_electorales_'), 'electoral', 'administrativo', 'P2'),
    (lambda n: n.startswith('g31_censo2020_'), 'censo', 'territorio', 'P0'),
    (lambda n: n.startswith('g31_censo2010_'), 'censo', 'territorio', 'P1'),
    (lambda n: n.startswith('g31_censo2000_'), 'censo', 'territorio', 'P2'),
    (lambda n: n.startswith('g31_censo1990_'), 'censo', 'territorio', 'P2'),
    (lambda n: n.startswith('g23_hidrografia_'), 'hidrografia', 'hidrografia', 'P1'),
    (lambda n: n.startswith('g23_lineales_'), 'hidrografia', 'hidrografia', 'P1'),
    (lambda n: n.startswith('g23_national_hydro_'), 'hidrografia', 'hidrografia', 'P1'),
    (lambda n: n.startswith('g23_nhd_watershed_'), 'hidrografia', 'hidrografia', 'P1'),
    (lambda n: n.startswith('g23_mapa_base_hidrografia'), 'hidrografia', 'hidrografia', 'P1'),
    (lambda n: n.startswith('g23_batimetria_lagos'), 'hidrografia', 'hidrografia', 'P1'),
    (lambda n: n.startswith('g23_humedales_'), 'humedales', 'ambiente', 'P1'),
    (lambda n: n.startswith('g23_puntuales_'), 'hidrografia', 'hidrografia', 'P2'),
    (lambda n: n.startswith('g23_areas_'), 'conservacion', 'ambiente', 'P2'),
    (lambda n: n.startswith('g23_agricultura_'), 'agricultura', 'ambiente', 'P1'),
    (lambda n: n.startswith('g15_geologia_gravity'), 'gravedad_magnetica', 'geologia', 'P2'),
    (lambda n: n.startswith('g15_geologia_magnetic'), 'gravedad_magnetica', 'geologia', 'P2'),
    (lambda n: n.startswith('
