"""
Greenfield least-cost path router — Phase 10.

Uses a grid-based Dijkstra (8-connectivity) over the cost surface built by
cost_surface.build_cost_surface().  Returns one or more RouteResult objects
that contain the waypoint path in EPSG:32161 coordinates plus a per-segment
cost breakdown.

Alternatives are generated by the "corridor exclusion" method: after each
found path, cells along it are inflated by a penalty multiplier so subsequent
Dijkstra runs find geographically distinct routes.
"""
from __future__ import annotations

import heapq
import logging
from dataclasses import dataclass, field

import numpy as np

from prism.corridor.cost_surface import CostSurface, TIER_FACTOR, terrain_type_at, idx_to_xy, xy_to_idx

log = logging.getLogger(__name__)

# Cells within this grid-cell radius of a found path are penalised for alternatives
_EXCLUSION_RADIUS = 5   # cells (~1.5 km at 300 m resolution)
_EXCLUSION_FACTOR = 8.0  # multiply cell cost along previous route


@dataclass
class Segment:
    terrain_type: str
    cost_per_km:  float    # USD / km for this terrain type
    km:           float
    coords:       list[tuple[float, float]]   # EPSG:32161 (x, y) pairs


@dataclass
class RouteResult:
    from_city:    str
    to_city:      str
    alternative:  int
    total_km:     float
    construction_cost_usd: float
    maintenance_30yr_usd:  float
    flood_exposure_frac:   float
    segments:     list[Segment] = field(default_factory=list)
    coords:       list[tuple[float, float]] = field(default_factory=list)  # full path

    @property
    def total_cost_usd(self) -> float:
        return self.construction_cost_usd + self.maintenance_30yr_usd


# Rail unit costs (USD / m)
_COST_PER_M: dict[str, float] = {
    "standard": 15_000_000 / 1_000,   # $15 M/km
    "elevated": 40_000_000 / 1_000,   # $40 M/km
    "tunnel":  120_000_000 / 1_000,   # $120 M/km
}
_MAINT_PER_M_YR = 500_000 / 1_000    # $500 K/km/yr
_NPV_30_5PCT    = 15.3725             # annuity factor 30 yr @ 5 %


def _dijkstra(
    cost: np.ndarray,
    start: tuple[int, int],
    end: tuple[int, int],
) -> list[tuple[int, int]] | None:
    """Grid Dijkstra with 8-connectivity.  Returns list of (row, col) or None."""
    nrows, ncols = cost.shape
    dist  = np.full((nrows, ncols), np.inf, dtype=np.float64)
    prev: dict[tuple[int, int], tuple[int, int]] = {}
    dist[start] = 0.0
    pq: list[tuple[float, tuple[int, int]]] = [(0.0, start)]

    while pq:
        d, cur = heapq.heappop(pq)
        if cur == end:
            break
        if d > dist[cur]:
            continue
        r, c = cur
        for dr in (-1, 0, 1):
            for dc in (-1, 0, 1):
                if dr == 0 and dc == 0:
                    continue
                nr, nc = r + dr, c + dc
                if not (0 <= nr < nrows and 0 <= nc < ncols):
                    continue
                # Diagonal moves cost √2 more
                move = cost[nr, nc] * (1.4142 if dr != 0 and dc != 0 else 1.0)
                nd = d + move
                if nd < dist[nr, nc]:
                    dist[nr, nc] = nd
                    prev[(nr, nc)] = cur
                    heapq.heappush(pq, (nd, (nr, nc)))

    if end not in prev and start != end:
        return None

    path: list[tuple[int, int]] = []
    cur = end
    while cur in prev:
        path.append(cur)
        cur = prev[cur]
    path.append(start)
    return list(reversed(path))


def _apply_exclusion(cost: np.ndarray, path: list[tuple[int, int]]) -> np.ndarray:
    """Return a copy of cost with cells near `path` inflated to discourage reuse."""
    penalised = cost.copy()
    nrows, ncols = cost.shape
    r = _EXCLUSION_RADIUS
    for row, col in path:
        rmin = max(0, row - r)
        rmax = min(nrows, row + r + 1)
        cmin = max(0, col - r)
        cmax = min(ncols, col + r + 1)
        penalised[rmin:rmax, cmin:cmax] *= _EXCLUSION_FACTOR
    return penalised


def _path_to_coords(
    path: list[tuple[int, int]],
    cs: CostSurface,
) -> list[tuple[float, float]]:
    return [idx_to_xy(r, c, cs) for r, c in path]


def _compute_segments(
    path:   list[tuple[int, int]],
    cs:     CostSurface,
) -> tuple[list[Segment], float, float, float]:
    """Compute per-terrain segments and totals.

    Returns (segments, total_km, construction_usd, maintenance_30yr_usd).
    Merges consecutive cells of the same terrain type into one segment.
    Each step (edge between consecutive path cells) is attributed to exactly
    one segment, so sum(segment.km) == the true path length (matches
    ST_Length of the full-path geometry within rounding).
    """
    res = cs.resolution_m
    segments: list[Segment] = []
    total_construction = 0.0
    total_maint = 0.0
    total_km = 0.0

    def _flush(terrain: str, coords: list[tuple[float, float]], km: float) -> None:
        nonlocal total_construction, total_maint, total_km
        c_per_m = _COST_PER_M[terrain]
        m = km * 1_000
        construction = c_per_m * m
        maint = _MAINT_PER_M_YR * m * _NPV_30_5PCT
        total_construction += construction
        total_maint += maint
        total_km += km
        segments.append(Segment(
            terrain_type=terrain,
            cost_per_km=c_per_m * 1_000,
            km=km,
            coords=list(coords),
        ))

    current_terrain = terrain_type_at(float(cs.slope_array[path[0]]))
    current_coords: list[tuple[float, float]] = [idx_to_xy(path[0][0], path[0][1], cs)]
    current_km = 0.0

    for i in range(1, len(path)):
        prev_row, prev_col = path[i - 1]
        row, col = path[i]
        diag = abs(row - prev_row) + abs(col - prev_col) == 2
        step_km = res * (1.4142 if diag else 1.0) / 1_000
        terrain = terrain_type_at(float(cs.slope_array[row, col]))
        xy = idx_to_xy(row, col, cs)

        if terrain != current_terrain:
            # The connecting edge belongs to the segment it leads into.
            current_coords.append(xy)
            current_km += step_km
            _flush(current_terrain, current_coords, current_km)
            current_terrain = terrain
            current_coords = [xy]
            current_km = 0.0
        else:
            current_km += step_km
            current_coords.append(xy)

    _flush(current_terrain, current_coords, current_km)

    return segments, total_km, total_construction, total_maint


def route(
    cs:           CostSurface,
    from_city:    str,
    to_city:      str,
    from_xy:      tuple[float, float],   # EPSG:32161
    to_xy:        tuple[float, float],   # EPSG:32161
    n_alternatives: int = 3,
) -> list[RouteResult]:
    """Find N least-cost-path alternatives between two points.

    Each alternative after the first uses an exclusion-penalised cost surface.
    """
    results: list[RouteResult] = []
    working_cost = cs.array.copy()

    start_idx = xy_to_idx(from_xy[0], from_xy[1], cs)
    end_idx   = xy_to_idx(to_xy[0],   to_xy[1],   cs)

    log.info(
        "Routing %s -> %s (%d alternatives); start=%s end=%s",
        from_city, to_city, n_alternatives, start_idx, end_idx,
    )

    for alt in range(1, n_alternatives + 1):
        path = _dijkstra(working_cost, start_idx, end_idx)
        if path is None:
            log.warning("No path found for %s -> %s alt %d", from_city, to_city, alt)
            break

        segments, total_km, construction, maint = _compute_segments(path, cs)

        # Flood exposure fraction
        flood_cells = sum(1 for r, c in path if cs.flood_array[r, c] > 0.5)
        flood_frac  = flood_cells / len(path) if path else 0.0

        coords = _path_to_coords(path, cs)

        results.append(RouteResult(
            from_city=from_city,
            to_city=to_city,
            alternative=alt,
            total_km=total_km,
            construction_cost_usd=construction,
            maintenance_30yr_usd=maint,
            flood_exposure_frac=flood_frac,
            segments=segments,
            coords=coords,
        ))

        log.info(
            "  Alt %d: %.1f km, construction $%.0fM, maint $%.0fM, flood %.1f%%",
            alt,
            total_km,
            construction / 1e6,
            maint / 1e6,
            flood_frac * 100,
        )

        # Penalise this path so the next alternative diverges
        working_cost = _apply_exclusion(working_cost, path)

    return results
