"use client";

import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Sparkles } from "lucide-react";

import { Skeleton } from "@/components/ui/skeleton";
import { cn, fmtDateTime } from "@/lib/utils";

export interface NarrativePanelProps {
  /** GitHub-flavored markdown narrative body — never render LLM output as a bare string. */
  markdown?: string | null;
  title?: string | null;
  modelUsed?: string | null;
  generatedAt?: string | null;
  status?: string | null;
  /** Skeleton placeholder for the initial fetch, before any content is available. */
  loading?: boolean;
  /** Hides the provenance footer and shows a blinking cursor while a stream is in flight. */
  streaming?: boolean;
  className?: string;
}

/** Renders AI narrative text as styled markdown with a "generated by" footer. */
export function NarrativePanel({
  markdown,
  title,
  modelUsed,
  generatedAt,
  status,
  loading,
  streaming,
  className,
}: NarrativePanelProps) {
  if (loading) {
    return (
      <div className={cn("space-y-2", className)}>
        <Skeleton className="h-4 w-2/3" />
        <Skeleton className="h-3 w-full" />
        <Skeleton className="h-3 w-full" />
        <Skeleton className="h-3 w-5/6" />
      </div>
    );
  }

  if (!markdown) return null;

  return (
    <div className={cn("space-y-2", className)}>
      {title && <h4 className="text-sm font-semibold text-foreground">{title}</h4>}
      <div
        className={cn(
          "prose prose-sm prose-invert max-w-none",
          "prose-headings:font-semibold prose-headings:text-foreground",
          "prose-h3:mb-1.5 prose-h3:mt-3 prose-h3:text-[11px] prose-h3:uppercase prose-h3:tracking-wider prose-h3:text-primary/80 first:prose-h3:mt-0",
          "prose-p:text-muted-foreground prose-li:text-muted-foreground prose-strong:text-foreground",
          "prose-table:text-xs prose-th:text-foreground prose-td:align-top",
        )}
      >
        <ReactMarkdown remarkPlugins={[remarkGfm]}>{markdown}</ReactMarkdown>
        {streaming && (
          <span className="ml-0.5 inline-block h-3.5 w-1.5 animate-pulse bg-primary/60 align-middle" />
        )}
      </div>
      {!streaming && (modelUsed || generatedAt) && (
        <div className="flex items-center gap-1.5 border-t border-border/50 pt-1.5 text-[10px] text-muted-foreground">
          <Sparkles className="h-3 w-3 shrink-0" />
          <span>
            Generated by {modelUsed ?? "unknown"}
            {generatedAt ? ` · ${fmtDateTime(generatedAt)}` : ""}
            {status === "failed" ? " · generation failed, showing fallback" : ""}
          </span>
        </div>
      )}
    </div>
  );
}
