/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness + DB reachability. Used by the container healthcheck.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Overview
         * @description Everything the landing page needs in one round trip.
         */
        get: operations["overview_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resilience/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenarios */
        get: operations["scenarios_resilience_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resilience/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scores
         * @description Scored substations for a scenario, with centroid lon/lat for the map.
         */
        get: operations["scores_resilience_scores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resilience/spof": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spof
         * @description Single points of failure: articulation points + top-betweenness entities.
         */
        get: operations["spof_resilience_spof_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resilience/substations/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Substation Detail
         * @description Full breakdown for the click-detail panel: score + cascade + exposure.
         */
        get: operations["substation_detail_resilience_substations__entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_portfolio_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Detail */
        get: operations["run_detail_portfolio_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/economy/tracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tracts
         * @description SVI choropleth: one Feature per Census tract.
         */
        get: operations["tracts_economy_tracts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/economy/community": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Community
         * @description Community resilience score per barrio (polygon choropleth).
         */
        get: operations["community_economy_community_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/economy/exposure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exposure
         * @description Substation VOLL exposure with centroid lon/lat for a bubble layer.
         */
        get: operations["exposure_economy_exposure_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corridor/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Routes
         * @description All corridor alternatives as summary rows (no geometry) for tables/selectors.
         */
        get: operations["routes_corridor_routes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corridor/routes/geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Routes Geojson
         * @description All route centerlines as a FeatureCollection for the map (rank in properties).
         */
        get: operations["routes_geojson_corridor_routes_geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corridor/routes/{route_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Route Detail
         * @description Single route: full objective breakdown + segment geometry + narrative (if any).
         */
        get: operations["route_detail_corridor_routes__route_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/network/transmission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Transmission
         * @description Transmission network, one MultiLineString feature per connected component.
         *
         *     Collecting by component (74 of them) keeps the payload ~2 MB while still
         *     drawing the full grid web; geometry is simplified to ~90 m and reprojected.
         */
        get: operations["transmission_network_transmission_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hazard/flood": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Flood
         * @description 1%-annual-chance flood zones as polygons.
         *
         *     Tiny slivers (< 5 ha) are dropped and geometry is simplified to ~120 m to
         *     keep the payload near 2 MB for a one-time cached overlay.
         */
        get: operations["flood_hazard_flood_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_sync_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Log */
        get: operations["log_sync_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/narratives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Narratives */
        get: operations["narratives_reports_narratives_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CorridorRoute */
        CorridorRoute: {
            /** Route Id */
            route_id: number;
            /** From City */
            from_city: string;
            /** To City */
            to_city: string;
            /** Alternative N */
            alternative_n: number;
            /** Total Km */
            total_km: number;
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Construction Cost Usd */
            construction_cost_usd: number | null;
            /** Maintenance 30Yr Usd */
            maintenance_30yr_usd: number | null;
            /** Flood Exposure Frac */
            flood_exposure_frac: number | null;
            /** Population Served */
            population_served: number | null;
            /** Svi Weighted Pop */
            svi_weighted_pop: number | null;
            /** Objective Score */
            objective_score: number | null;
            /** Rank */
            rank: number;
        };
        /** CorridorRouteDetail */
        CorridorRouteDetail: {
            /** Route Id */
            route_id: number;
            /** From City */
            from_city: string;
            /** To City */
            to_city: string;
            /** Alternative N */
            alternative_n: number;
            /** Total Km */
            total_km: number;
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Construction Cost Usd */
            construction_cost_usd: number | null;
            /** Maintenance 30Yr Usd */
            maintenance_30yr_usd: number | null;
            /** Flood Exposure Frac */
            flood_exposure_frac: number | null;
            /** Population Served */
            population_served: number | null;
            /** Svi Weighted Pop */
            svi_weighted_pop: number | null;
            /** Objective Score */
            objective_score: number | null;
            /** Rank */
            rank: number;
            segments_geojson: components["schemas"]["FeatureCollection"];
            line_geojson: components["schemas"]["FeatureCollection"];
            /** Segments */
            segments: components["schemas"]["CorridorSegment"][];
            /** Narrative */
            narrative?: string | null;
        };
        /** CorridorSegment */
        CorridorSegment: {
            /** Segment Id */
            segment_id: number;
            /** Seq */
            seq: number;
            /** Terrain Type */
            terrain_type: string | null;
            /** Cost Per Km */
            cost_per_km: number | null;
            /** Km */
            km: number | null;
        };
        /** ExposureRow */
        ExposureRow: {
            /** Entity Id */
            entity_id: number;
            /** Entity Name */
            entity_name: string | null;
            /** Population Affected */
            population_affected: number | null;
            /** Daily Economic Value Usd */
            daily_economic_value_usd: number | null;
            /** Population Benefit Usd */
            population_benefit_usd: number | null;
            /** Economic Benefit Usd */
            economic_benefit_usd: number | null;
            /** Property Impact Usd */
            property_impact_usd: number | null;
            /** Lon */
            lon?: number | null;
            /** Lat */
            lat?: number | null;
        };
        /** Feature */
        Feature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            /** Geometry */
            geometry?: {
                [key: string]: unknown;
            } | null;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
        };
        /** FeatureCollection */
        FeatureCollection: {
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
            /** Features */
            features?: components["schemas"]["Feature"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Database */
            database: string;
            /** Postgis */
            postgis?: string | null;
        };
        /** Narrative */
        Narrative: {
            /** Narrative Id */
            narrative_id: number;
            /** Scenario Name */
            scenario_name: string | null;
            /** Run Id */
            run_id: number | null;
            /** Title */
            title: string | null;
            /** Text */
            text: string | null;
            /** Equity Flag */
            equity_flag: boolean | null;
            /** Model Used */
            model_used: string | null;
            /** Generated At */
            generated_at: string | null;
        };
        /** OverviewCounts */
        OverviewCounts: {
            /** Substations Scored */
            substations_scored: number;
            /** Economy Tracts */
            economy_tracts: number;
            /** Corridor Routes */
            corridor_routes: number;
            /** Portfolio Runs */
            portfolio_runs: number;
            /** Graph Entities */
            graph_entities: number;
            /** Graph Relationships */
            graph_relationships: number;
            /** Sync Sources */
            sync_sources: number;
            /** Barrios Access */
            barrios_access: number;
        };
        /** OverviewResponse */
        OverviewResponse: {
            counts: components["schemas"]["OverviewCounts"];
            /** Last Sync At */
            last_sync_at?: string | null;
            /** Top Substation */
            top_substation?: string | null;
            /** Top Substation Score */
            top_substation_score?: number | null;
            /** Scenarios */
            scenarios: string[];
            /** Phases */
            phases: components["schemas"]["PhaseStatus"][];
        };
        /** PhaseStatus */
        PhaseStatus: {
            /** Phase */
            phase: number;
            /** Name */
            name: string;
            /** Status */
            status: string;
        };
        /** PortfolioItem */
        PortfolioItem: {
            /** Item Id */
            item_id: number;
            /** Priority */
            priority: number | null;
            /** Entity Id */
            entity_id: number;
            /** Entity Name */
            entity_name: string | null;
            /** Intervention Type */
            intervention_type: string;
            /** Cost Usd */
            cost_usd: number;
            /** Resilience Uplift */
            resilience_uplift: number | null;
            /** Uplift Per Million */
            uplift_per_million: number | null;
            /** Cumulative Cost Usd */
            cumulative_cost_usd: number | null;
            /** Cumulative Uplift */
            cumulative_uplift: number | null;
        };
        /** PortfolioRun */
        PortfolioRun: {
            /** Run Id */
            run_id: number;
            /** Scenario Name */
            scenario_name: string;
            /** Budget Usd */
            budget_usd: number;
            /** Algorithm */
            algorithm: string | null;
            /** Total Cost Usd */
            total_cost_usd: number | null;
            /** Total Uplift */
            total_uplift: number | null;
            /** N Interventions */
            n_interventions: number | null;
            /** Computed At */
            computed_at: string | null;
        };
        /** PortfolioRunDetail */
        PortfolioRunDetail: {
            /** Run Id */
            run_id: number;
            /** Scenario Name */
            scenario_name: string;
            /** Budget Usd */
            budget_usd: number;
            /** Algorithm */
            algorithm: string | null;
            /** Total Cost Usd */
            total_cost_usd: number | null;
            /** Total Uplift */
            total_uplift: number | null;
            /** N Interventions */
            n_interventions: number | null;
            /** Computed At */
            computed_at: string | null;
            /** Items */
            items: components["schemas"]["PortfolioItem"][];
            /** Allocation By Type */
            allocation_by_type: components["schemas"]["TypeAllocation"][];
        };
        /** ScenarioInfo */
        ScenarioInfo: {
            /** Name */
            name: string;
            /** N Scored */
            n_scored: number;
            /** Min Score */
            min_score: number;
            /** Max Score */
            max_score: number;
        };
        /** SpofEntity */
        SpofEntity: {
            /** Entity Id */
            entity_id: number;
            /** Name */
            name: string | null;
            /** Kind */
            kind: string | null;
            /** Betweenness */
            betweenness: number;
            /** Is Articulation */
            is_articulation: boolean;
            /** Lon */
            lon?: number | null;
            /** Lat */
            lat?: number | null;
        };
        /** SubstationDetail */
        SubstationDetail: {
            /** Entity Id */
            entity_id: number;
            /** Name */
            name: string | null;
            /** Composite Score */
            composite_score: number;
            /** Hazard Score */
            hazard_score: number | null;
            /** Cascade Impact */
            cascade_impact: number | null;
            /** Spof Betweenness */
            spof_betweenness: number | null;
            /** Rank */
            rank: number | null;
            /** Is Articulation */
            is_articulation: boolean;
            /** Lon */
            lon: number;
            /** Lat */
            lat: number;
            /** Scenario */
            scenario: string;
            /** Downstream Hospitals */
            downstream_hospitals?: number | null;
            /** Downstream Water Plants */
            downstream_water_plants?: number | null;
            /** Downstream Health Centers */
            downstream_health_centers?: number | null;
            /** Downstream Barrios */
            downstream_barrios?: number | null;
            /** Population Affected */
            population_affected?: number | null;
            /** Population Benefit Usd */
            population_benefit_usd?: number | null;
            /** Economic Benefit Usd */
            economic_benefit_usd?: number | null;
        };
        /** SubstationScore */
        SubstationScore: {
            /** Entity Id */
            entity_id: number;
            /** Name */
            name: string | null;
            /** Composite Score */
            composite_score: number;
            /** Hazard Score */
            hazard_score: number | null;
            /** Cascade Impact */
            cascade_impact: number | null;
            /** Spof Betweenness */
            spof_betweenness: number | null;
            /** Rank */
            rank: number | null;
            /** Is Articulation */
            is_articulation: boolean;
            /** Lon */
            lon: number;
            /** Lat */
            lat: number;
        };
        /** SyncLogEntry */
        SyncLogEntry: {
            /** Run Id */
            run_id: number;
            /** Source Name */
            source_name: string;
            /** Rows Updated */
            rows_updated: number | null;
            /** Duration S */
            duration_s: number | null;
            /** Status */
            status: string | null;
            /** Triggered Rescore */
            triggered_rescore: boolean | null;
            /** Error Msg */
            error_msg: string | null;
            /** Run At */
            run_at: string | null;
        };
        /** SyncSource */
        SyncSource: {
            /** Id */
            id: number;
            /** Source Name */
            source_name: string;
            /** Source Type */
            source_type: string | null;
            /** Layer Name */
            layer_name: string | null;
            /** Url */
            url: string | null;
            /** Sync Interval Hours */
            sync_interval_hours: number | null;
            /** Last Fetched At */
            last_fetched_at: string | null;
            /** Last Checksum */
            last_checksum: string | null;
            /** Row Count */
            row_count: number | null;
            /** Status */
            status: string | null;
        };
        /** TypeAllocation */
        TypeAllocation: {
            /** Intervention Type */
            intervention_type: string;
            /** N */
            n: number;
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Total Uplift */
            total_uplift: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    overview_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
        };
    };
    scenarios_resilience_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioInfo"][];
                };
            };
        };
    };
    scores_resilience_scores_get: {
        parameters: {
            query?: {
                scenario?: string;
                top?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubstationScore"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spof_resilience_spof_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpofEntity"][];
                };
            };
        };
    };
    substation_detail_resilience_substations__entity_id__get: {
        parameters: {
            query?: {
                scenario?: string;
            };
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubstationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_portfolio_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioRun"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_detail_portfolio_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tracts_economy_tracts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
        };
    };
    community_economy_community_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
        };
    };
    exposure_economy_exposure_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExposureRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    routes_corridor_routes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorridorRoute"][];
                };
            };
        };
    };
    routes_geojson_corridor_routes_geojson_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
        };
    };
    route_detail_corridor_routes__route_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                route_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorridorRouteDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transmission_network_transmission_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
        };
    };
    flood_hazard_flood_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
        };
    };
    sources_sync_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncSource"][];
                };
            };
        };
    };
    log_sync_log_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncLogEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    narratives_reports_narratives_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Narrative"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
