/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness + DB reachability. Used by the container healthcheck.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Overview
         * @description Everything the landing page needs in one round trip.
         */
        get: operations["overview_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resilience/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenarios */
        get: operations["scenarios_resilience_scenarios_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resilience/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scores
         * @description Scored substations for a scenario, with centroid lon/lat for the map.
         */
        get: operations["scores_resilience_scores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resilience/spof": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Spof
         * @description Single points of failure: articulation points + top-betweenness entities.
         */
        get: operations["spof_resilience_spof_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resilience/substations/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Substation Detail
         * @description Full breakdown for the click-detail panel: score + cascade + exposure.
         */
        get: operations["substation_detail_resilience_substations__entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runs */
        get: operations["runs_portfolio_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Run Detail */
        get: operations["run_detail_portfolio_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/economy/tracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tracts
         * @description SVI choropleth: one Feature per Census tract.
         */
        get: operations["tracts_economy_tracts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/economy/community": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Community
         * @description Community resilience score per barrio (polygon choropleth).
         */
        get: operations["community_economy_community_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/economy/exposure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Exposure
         * @description Substation VOLL exposure with centroid lon/lat for a bubble layer.
         */
        get: operations["exposure_economy_exposure_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corridor/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Routes
         * @description All corridor alternatives as summary rows (no geometry) for tables/selectors.
         */
        get: operations["routes_corridor_routes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corridor/routes/geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Routes Geojson
         * @description All route centerlines as a FeatureCollection for the map (rank in properties).
         */
        get: operations["routes_geojson_corridor_routes_geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corridor/routes/{route_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Route Detail
         * @description Single route: full objective breakdown + segment geometry + narrative (if any).
         */
        get: operations["route_detail_corridor_routes__route_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corridor/routes/{route_id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Route Profile
         * @description DEM-sampled elevation profile along the route (~100 m intervals).
         */
        get: operations["route_profile_corridor_routes__route_id__profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/network/transmission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Transmission
         * @description Transmission network, one MultiLineString feature per connected component.
         *
         *     Collecting by component (74 of them) keeps the payload ~2 MB while still
         *     drawing the full grid web; geometry is simplified to ~90 m and reprojected.
         */
        get: operations["transmission_network_transmission_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hazard/flood": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Flood
         * @description 1%-annual-chance flood zones as polygons.
         *
         *     Tiny slivers (< 5 ha) are dropped and geometry is simplified to ~120 m to
         *     keep the payload near 2 MB for a one-time cached overlay.
         */
        get: operations["flood_hazard_flood_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_sync_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sync/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Log */
        get: operations["log_sync_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/narratives": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Narratives */
        get: operations["narratives_reports_narratives_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/narratives/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Narratives Stream
         * @description SSE stream of a generated narrative: `event: chunk` messages with
         *     `{"text": "..."}` as markdown arrives, then one `event: done` message
         *     with `{"narrative_id", "model", "status", "title"}` once persisted.
         */
        post: operations["narratives_stream_reports_narratives_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/terrain/tiles/{z}/{x}/{y}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Terrain Tile
         * @description Return a MapLibre terrain-RGB PNG tile from locally-mirrored USGS 3DEP DEMs.
         */
        get: operations["terrain_tile_terrain_tiles__z___x___y__png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tiles/{layer}/{z}/{x}/{y}.mvt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tile
         * @description Return one MVT tile for `layer`, cached in Redis under `tiles:{layer}:{z}:{x}:{y}`.
         */
        get: operations["tile_tiles__layer___z___x___y__mvt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/corridor/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue Corridor Regen */
        post: operations["enqueue_corridor_regen_jobs_corridor_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/resilience/rescore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue Rescore */
        post: operations["enqueue_rescore_jobs_resilience_rescore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/narratives/corridor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue Corridor Narrative */
        post: operations["enqueue_corridor_narrative_jobs_narratives_corridor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Job Status */
        get: operations["job_status_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playground/asset-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Asset Types
         * @description All asset types the Playground palette can draw, reflected from prism.assets.*.
         */
        get: operations["asset_types_playground_asset_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playground/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_playground_scenarios_get"];
        put?: never;
        /** Create Scenario */
        post: operations["create_scenario_playground_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playground/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario */
        get: operations["get_scenario_playground_scenarios__scenario_id__get"];
        put?: never;
        post?: never;
        /** Delete Scenario */
        delete: operations["delete_scenario_playground_scenarios__scenario_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playground/scenarios/{scenario_id}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit Scenario
         * @description Mark a scenario as a committed reference plan.
         *
         *     The one explicit exception to "Playground never mutates base tables":
         *     drafted `rail` line assets get station entities written into
         *     `graph.entities` (+ SERVES relationships to the nearest barrio).
         *     Idempotent — re-committing updates existing stations in place.
         */
        post: operations["commit_scenario_playground_scenarios__scenario_id__commit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playground/scenarios/{scenario_id}/assets/geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scenario Assets Geojson */
        get: operations["scenario_assets_geojson_playground_scenarios__scenario_id__assets_geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playground/scenarios/{scenario_id}/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Scenario Asset */
        post: operations["add_scenario_asset_playground_scenarios__scenario_id__assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playground/scenarios/{scenario_id}/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Scenario Asset */
        delete: operations["delete_scenario_asset_playground_scenarios__scenario_id__assets__asset_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playground/scenarios/{scenario_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Scenario Event */
        post: operations["add_scenario_event_playground_scenarios__scenario_id__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playground/scenarios/{scenario_id}/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Scenario Event */
        delete: operations["delete_scenario_event_playground_scenarios__scenario_id__events__event_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playground/scenarios/{scenario_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Result */
        get: operations["latest_result_playground_scenarios__scenario_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playground/scenarios/{scenario_id}/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue Evaluate */
        post: operations["enqueue_evaluate_playground_scenarios__scenario_id__evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playground/whatif/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue Whatif */
        post: operations["enqueue_whatif_playground_whatif__entity_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/playground/scenarios/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enqueue Comparison Narrative */
        post: operations["enqueue_comparison_narrative_playground_scenarios_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssetTypeSchema
         * @description A playground-eligible asset type, reflected from PLAYGROUND_SCHEMA.
         */
        AssetTypeSchema: {
            /** Asset Type */
            asset_type: string;
            /**
             * Geometry
             * @enum {string}
             */
            geometry: "point" | "line";
            /** Icon */
            icon: string;
            /** Default Unit Cost Usd Per Km */
            default_unit_cost_usd_per_km?: number | null;
            /** Default Unit Cost Usd */
            default_unit_cost_usd?: number | null;
            /** Params */
            params?: {
                [key: string]: unknown;
            }[];
        };
        /** CommitResult */
        CommitResult: {
            /** Scenario Id */
            scenario_id: number;
            /** Stations Created */
            stations_created: number;
            /** Serves Created */
            serves_created: number;
        };
        /** CorridorRoute */
        CorridorRoute: {
            /** Route Id */
            route_id: number;
            /** From City */
            from_city: string;
            /** To City */
            to_city: string;
            /** Alternative N */
            alternative_n: number;
            /** Total Km */
            total_km: number;
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Construction Cost Usd */
            construction_cost_usd: number | null;
            /** Maintenance 30Yr Usd */
            maintenance_30yr_usd: number | null;
            /** Flood Exposure Frac */
            flood_exposure_frac: number | null;
            /** Population Served */
            population_served: number | null;
            /** Svi Weighted Pop */
            svi_weighted_pop: number | null;
            /** Objective Score */
            objective_score: number | null;
            /** Rank */
            rank: number;
        };
        /** CorridorRouteDetail */
        CorridorRouteDetail: {
            /** Route Id */
            route_id: number;
            /** From City */
            from_city: string;
            /** To City */
            to_city: string;
            /** Alternative N */
            alternative_n: number;
            /** Total Km */
            total_km: number;
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Construction Cost Usd */
            construction_cost_usd: number | null;
            /** Maintenance 30Yr Usd */
            maintenance_30yr_usd: number | null;
            /** Flood Exposure Frac */
            flood_exposure_frac: number | null;
            /** Population Served */
            population_served: number | null;
            /** Svi Weighted Pop */
            svi_weighted_pop: number | null;
            /** Objective Score */
            objective_score: number | null;
            /** Rank */
            rank: number;
            segments_geojson: components["schemas"]["FeatureCollection"];
            line_geojson: components["schemas"]["FeatureCollection"];
            /** Segments */
            segments: components["schemas"]["CorridorSegment"][];
            narrative?: components["schemas"]["NarrativeContent"] | null;
        };
        /** CorridorSegment */
        CorridorSegment: {
            /** Segment Id */
            segment_id: number;
            /** Seq */
            seq: number;
            /** Terrain Type */
            terrain_type: string | null;
            /** Cost Per Km */
            cost_per_km: number | null;
            /** Km */
            km: number | null;
        };
        /** ExposureRow */
        ExposureRow: {
            /** Entity Id */
            entity_id: number;
            /** Entity Name */
            entity_name: string | null;
            /** Population Affected */
            population_affected: number | null;
            /** Daily Economic Value Usd */
            daily_economic_value_usd: number | null;
            /** Population Benefit Usd */
            population_benefit_usd: number | null;
            /** Economic Benefit Usd */
            economic_benefit_usd: number | null;
            /** Property Impact Usd */
            property_impact_usd: number | null;
            /** Lon */
            lon?: number | null;
            /** Lat */
            lat?: number | null;
        };
        /** Feature */
        Feature: {
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
            /** Geometry */
            geometry?: {
                [key: string]: unknown;
            } | null;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
        };
        /** FeatureCollection */
        FeatureCollection: {
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
            /** Features */
            features?: components["schemas"]["Feature"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Database */
            database: string;
            /** Postgis */
            postgis?: string | null;
        };
        /** JobEnqueued */
        JobEnqueued: {
            /** Job Id */
            job_id: string;
        };
        /** JobStatusResponse */
        JobStatusResponse: {
            /** Job Id */
            job_id: string;
            /** Status */
            status: string;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
        };
        /** Narrative */
        Narrative: {
            /** Narrative Id */
            narrative_id: number;
            /** Scenario Name */
            scenario_name: string | null;
            /** Run Id */
            run_id: number | null;
            /** Title */
            title: string | null;
            /** Text */
            text: string | null;
            /** Equity Flag */
            equity_flag: boolean | null;
            /** Model Used */
            model_used: string | null;
            /** Format */
            format?: string | null;
            /** Status */
            status?: string | null;
            /** Generated At */
            generated_at: string | null;
        };
        /**
         * NarrativeContent
         * @description Parsed narrative ready for the frontend NarrativePanel — markdown body
         *     plus the provenance footer (model + timestamp).
         */
        NarrativeContent: {
            /** Title */
            title?: string | null;
            /** Narrative Md */
            narrative_md: string;
            /**
             * Format
             * @default markdown
             */
            format: string;
            /** Model Used */
            model_used?: string | null;
            /** Status */
            status?: string | null;
            /** Generated At */
            generated_at?: string | null;
        };
        /** OverviewCounts */
        OverviewCounts: {
            /** Substations Scored */
            substations_scored: number;
            /** Economy Tracts */
            economy_tracts: number;
            /** Corridor Routes */
            corridor_routes: number;
            /** Portfolio Runs */
            portfolio_runs: number;
            /** Graph Entities */
            graph_entities: number;
            /** Graph Relationships */
            graph_relationships: number;
            /** Sync Sources */
            sync_sources: number;
            /** Barrios Access */
            barrios_access: number;
        };
        /** OverviewResponse */
        OverviewResponse: {
            counts: components["schemas"]["OverviewCounts"];
            /** Last Sync At */
            last_sync_at?: string | null;
            /** Top Substation */
            top_substation?: string | null;
            /** Top Substation Score */
            top_substation_score?: number | null;
            /** Scenarios */
            scenarios: string[];
            /** Phases */
            phases: components["schemas"]["PhaseStatus"][];
        };
        /** PhaseStatus */
        PhaseStatus: {
            /** Phase */
            phase: number;
            /** Name */
            name: string;
            /** Status */
            status: string;
        };
        /** PlaygroundScenario */
        PlaygroundScenario: {
            /** Scenario Id */
            scenario_id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Author */
            author: string | null;
            /** Status */
            status: string;
            /** Is Reference */
            is_reference: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PlaygroundScenarioDetail */
        PlaygroundScenarioDetail: {
            /** Scenario Id */
            scenario_id: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Author */
            author: string | null;
            /** Status */
            status: string;
            /** Is Reference */
            is_reference: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Assets */
            assets: components["schemas"]["ScenarioAsset"][];
            /** Events */
            events: components["schemas"]["ScenarioEvent"][];
            latest_result?: components["schemas"]["ScenarioResult"] | null;
        };
        /** PortfolioItem */
        PortfolioItem: {
            /** Item Id */
            item_id: number;
            /** Priority */
            priority: number | null;
            /** Entity Id */
            entity_id: number;
            /** Entity Name */
            entity_name: string | null;
            /** Intervention Type */
            intervention_type: string;
            /** Cost Usd */
            cost_usd: number;
            /** Resilience Uplift */
            resilience_uplift: number | null;
            /** Uplift Per Million */
            uplift_per_million: number | null;
            /** Cumulative Cost Usd */
            cumulative_cost_usd: number | null;
            /** Cumulative Uplift */
            cumulative_uplift: number | null;
        };
        /** PortfolioRun */
        PortfolioRun: {
            /** Run Id */
            run_id: number;
            /** Scenario Name */
            scenario_name: string;
            /** Budget Usd */
            budget_usd: number;
            /** Algorithm */
            algorithm: string | null;
            /** Total Cost Usd */
            total_cost_usd: number | null;
            /** Total Uplift */
            total_uplift: number | null;
            /** N Interventions */
            n_interventions: number | null;
            /** Computed At */
            computed_at: string | null;
        };
        /** PortfolioRunDetail */
        PortfolioRunDetail: {
            /** Run Id */
            run_id: number;
            /** Scenario Name */
            scenario_name: string;
            /** Budget Usd */
            budget_usd: number;
            /** Algorithm */
            algorithm: string | null;
            /** Total Cost Usd */
            total_cost_usd: number | null;
            /** Total Uplift */
            total_uplift: number | null;
            /** N Interventions */
            n_interventions: number | null;
            /** Computed At */
            computed_at: string | null;
            /** Items */
            items: components["schemas"]["PortfolioItem"][];
            /** Allocation By Type */
            allocation_by_type: components["schemas"]["TypeAllocation"][];
        };
        /** ProfilePoint */
        ProfilePoint: {
            /** Distance M */
            distance_m: number;
            /** Lng */
            lng: number;
            /** Lat */
            lat: number;
            /** Elev M */
            elev_m: number;
            /** Grade Pct */
            grade_pct: number;
            /** Terrain Type */
            terrain_type: string;
        };
        /** ScenarioAsset */
        ScenarioAsset: {
            /** Asset Id */
            asset_id: number;
            /** Asset Type */
            asset_type: string;
            /** Op */
            op: string;
            /** Target Entity Id */
            target_entity_id: number | null;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ScenarioAssetCreate */
        ScenarioAssetCreate: {
            /** Asset Type */
            asset_type: string;
            /**
             * Op
             * @default add
             * @enum {string}
             */
            op: "add" | "remove";
            /** Geometry */
            geometry?: {
                [key: string]: unknown;
            } | null;
            /** Target Entity Id */
            target_entity_id?: number | null;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
        };
        /** ScenarioCreate */
        ScenarioCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Author */
            author?: string | null;
        };
        /** ScenarioEvent */
        ScenarioEvent: {
            /** Event Id */
            event_id: number;
            /** Entity Id */
            entity_id: number;
            /** Event Type */
            event_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ScenarioEventCreate */
        ScenarioEventCreate: {
            /** Entity Id */
            entity_id: number;
            /**
             * Event Type
             * @default fail
             * @constant
             */
            event_type: "fail";
        };
        /** ScenarioInfo */
        ScenarioInfo: {
            /** Name */
            name: string;
            /** N Scored */
            n_scored: number;
            /** Min Score */
            min_score: number;
            /** Max Score */
            max_score: number;
        };
        /** ScenarioResult */
        ScenarioResult: {
            /** Result Id */
            result_id: number;
            /** Scenario Id */
            scenario_id: number;
            /** Run Id */
            run_id: string | null;
            /** Objective Breakdown */
            objective_breakdown: {
                [key: string]: unknown;
            } | null;
            /** Resilience Delta */
            resilience_delta: {
                [key: string]: unknown;
            } | null;
            /** Headline */
            headline: string | null;
            /** Status */
            status: string;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
        };
        /** ConsequenceEntity */
        ConsequenceEntity: {
            /** Entity Id */
            entity_id: number;
            /** Kind */
            kind: string;
            /** Name */
            name: string | null;
            /** Lon */
            lon?: number | null;
            /** Lat */
            lat?: number | null;
        };
        /** ConsequenceSummary */
        ConsequenceSummary: {
            /** Entity Id */
            entity_id: number;
            /** Kind */
            kind: string;
            /** Name */
            name: string | null;
            /** Population Affected */
            population_affected: number;
            /** Hospitals */
            hospitals: number;
            /** Water Plants */
            water_plants: number;
            /** Health Centers */
            health_centers: number;
            /** Barrios */
            barrios: number;
            /** Headline */
            headline: string;
            /** Downstream */
            downstream: components["schemas"]["ConsequenceEntity"][];
        };
        /** SpofEntity */
        SpofEntity: {
            /** Entity Id */
            entity_id: number;
            /** Name */
            name: string | null;
            /** Kind */
            kind: string | null;
            /** Betweenness */
            betweenness: number;
            /** Is Articulation */
            is_articulation: boolean;
            /** Lon */
            lon?: number | null;
            /** Lat */
            lat?: number | null;
        };
        /** SubstationDetail */
        SubstationDetail: {
            /** Entity Id */
            entity_id: number;
            /** Name */
            name: string | null;
            /** Composite Score */
            composite_score: number;
            /** Hazard Score */
            hazard_score: number | null;
            /** Cascade Impact */
            cascade_impact: number | null;
            /** Spof Betweenness */
            spof_betweenness: number | null;
            /** Rank */
            rank: number | null;
            /** Is Articulation */
            is_articulation: boolean;
            /** Lon */
            lon: number;
            /** Lat */
            lat: number;
            /** Scenario */
            scenario: string;
            /** Downstream Hospitals */
            downstream_hospitals?: number | null;
            /** Downstream Water Plants */
            downstream_water_plants?: number | null;
            /** Downstream Health Centers */
            downstream_health_centers?: number | null;
            /** Downstream Barrios */
            downstream_barrios?: number | null;
            /** Population Affected */
            population_affected?: number | null;
            /** Population Benefit Usd */
            population_benefit_usd?: number | null;
            /** Economic Benefit Usd */
            economic_benefit_usd?: number | null;
        };
        /** SubstationScore */
        SubstationScore: {
            /** Entity Id */
            entity_id: number;
            /** Name */
            name: string | null;
            /** Composite Score */
            composite_score: number;
            /** Hazard Score */
            hazard_score: number | null;
            /** Cascade Impact */
            cascade_impact: number | null;
            /** Spof Betweenness */
            spof_betweenness: number | null;
            /** Rank */
            rank: number | null;
            /** Is Articulation */
            is_articulation: boolean;
            /** Lon */
            lon: number;
            /** Lat */
            lat: number;
        };
        /** SyncLogEntry */
        SyncLogEntry: {
            /** Run Id */
            run_id: number;
            /** Source Name */
            source_name: string;
            /** Rows Updated */
            rows_updated: number | null;
            /** Duration S */
            duration_s: number | null;
            /** Status */
            status: string | null;
            /** Triggered Rescore */
            triggered_rescore: boolean | null;
            /** Error Msg */
            error_msg: string | null;
            /** Run At */
            run_at: string | null;
        };
        /** SyncSource */
        SyncSource: {
            /** Id */
            id: number;
            /** Source Name */
            source_name: string;
            /** Source Type */
            source_type: string | null;
            /** Layer Name */
            layer_name: string | null;
            /** Url */
            url: string | null;
            /** Sync Interval Hours */
            sync_interval_hours: number | null;
            /** Last Fetched At */
            last_fetched_at: string | null;
            /** Last Checksum */
            last_checksum: string | null;
            /** Row Count */
            row_count: number | null;
            /** Status */
            status: string | null;
        };
        /** TypeAllocation */
        TypeAllocation: {
            /** Intervention Type */
            intervention_type: string;
            /** N */
            n: number;
            /** Total Cost Usd */
            total_cost_usd: number;
            /** Total Uplift */
            total_uplift: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    overview_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
        };
    };
    scenarios_resilience_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioInfo"][];
                };
            };
        };
    };
    scores_resilience_scores_get: {
        parameters: {
            query?: {
                scenario?: string;
                top?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubstationScore"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    spof_resilience_spof_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpofEntity"][];
                };
            };
        };
    };
    substation_detail_resilience_substations__entity_id__get: {
        parameters: {
            query?: {
                scenario?: string;
            };
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubstationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    runs_portfolio_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioRun"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_detail_portfolio_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioRunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tracts_economy_tracts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
        };
    };
    community_economy_community_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
        };
    };
    exposure_economy_exposure_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExposureRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    routes_corridor_routes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorridorRoute"][];
                };
            };
        };
    };
    routes_geojson_corridor_routes_geojson_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
        };
    };
    route_detail_corridor_routes__route_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                route_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorridorRouteDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_profile_corridor_routes__route_id__profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                route_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfilePoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transmission_network_transmission_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
        };
    };
    flood_hazard_flood_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
        };
    };
    sources_sync_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncSource"][];
                };
            };
        };
    };
    log_sync_log_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncLogEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    narratives_reports_narratives_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Narrative"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    narratives_stream_reports_narratives_stream_post: {
        parameters: {
            query?: {
                /** @description Narrative type to stream. Only 'corridor' is supported. */
                kind?: string;
                flagship?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    terrain_tile_terrain_tiles__z___x___y__png_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tile_tiles__layer___z___x___y__mvt_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer: string;
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_corridor_regen_jobs_corridor_regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueued"];
                };
            };
        };
    };
    enqueue_rescore_jobs_resilience_rescore_post: {
        parameters: {
            query?: {
                scenario?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_corridor_narrative_jobs_narratives_corridor_post: {
        parameters: {
            query?: {
                flagship?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_status_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    asset_types_playground_asset_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetTypeSchema"][];
                };
            };
        };
    };
    list_scenarios_playground_scenarios_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaygroundScenario"][];
                };
            };
        };
    };
    create_scenario_playground_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaygroundScenario"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenario_playground_scenarios__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaygroundScenarioDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scenario_playground_scenarios__scenario_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    commit_scenario_playground_scenarios__scenario_id__commit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenario_assets_geojson_playground_scenarios__scenario_id__assets_geojson_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureCollection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_scenario_asset_playground_scenarios__scenario_id__assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioAssetCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioAsset"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scenario_asset_playground_scenarios__scenario_id__assets__asset_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: number;
                asset_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_scenario_event_playground_scenarios__scenario_id__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioEventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scenario_event_playground_scenarios__scenario_id__events__event_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: number;
                event_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_result_playground_scenarios__scenario_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_evaluate_playground_scenarios__scenario_id__evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_whatif_playground_whatif__entity_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enqueue_comparison_narrative_playground_scenarios_compare_post: {
        parameters: {
            query: {
                scenario_a: number;
                scenario_b: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEnqueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
